name: Check Secrets / manual

on: workflow_dispatch

jobs:
  check-environment-secret:
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - name: check if test_secret in environment is valid
        run: echo ${{ secrets.TEST_SECRET == 'environment-secrets-test' }}
  check-repo-secret:
    runs-on: ubuntu-latest
    steps:
      - name: check if test_secret in repository is valid
        run: echo ${{ secrets.TEST_SECRET == 'repository-secrets-test' }}
