name: Check Secrets / manual

on: workflow_dispatch

jobs:
  check-environment-secret:
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - run: echo "Testing environment secret"
      - name: Fail job if test_secret in environment is invalid
        if: ${{ secrets.TEST_SECRET != 'environment-secrets-test' }}
        run: exit 1

  check-repo-secret:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing environment secret"
      - name: Fail job if test_secret in environment is invalid
        if: ${{ secrets.TEST_SECRET != 'repository-secrets-test' }}
        run: exit 1
