name: Check Secrets / manual

on: workflow_dispatch

jobs:
  check-environment-secret:
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
      - name: Check if test_secret in environment is invalid
        id: check-secret
        run: echo '::set-output name=validity::${{ secrets.TEST_SECRET == 'environment-secrets-test' }}'
      - name: Fail job if secret is invalid
        if: ${{ steps.check-secret.outputs.validity != 'true' }}
        run: exit 1


  check-repo-secret:
    runs-on: ubuntu-latest
    steps:
      - run: ${{ secrets.TEST_SECRET != 'environment-secrets-test' }}
      - name: Check if test_secret in environment is invalid
        id: check-secret
        run: echo '::set-output name=validity::${{ secrets.TEST_SECRET == 'repository-secrets-test' }}'
      - name: Fail job if secret is invalid
        if: ${{ steps.check-secret.outputs.validity != 'true' }}
        run: exit 1
