name: Run cron jobs

on:
  schedule:
    - cron: "*/10 * * * *" 

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci
    strategy:
      fail-fast: false
      matrix:
        name:
          [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
          ]
    steps:
      - run: echo ${{ matrix.name }}
      - name: Sleep
        run: sleep 600s
        shell: bash
      - run: exit 1
