name: Test / forks

on:
  pull_request_target:
    branches: [main]
    types: [labeled]

permissions:
  pull-requests: write # used to remove label
  # other permissions are defaulted to "none"

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - name: Remove run-tests label
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;
            const label = 'run-tests';
            github.issues.removeLabel({ owner, repo, issue_number, name: label });
      - name: echo ref
        run: echo ${{ github.event.pull_request.head.sha }}
      - name: Sleep for 120 seconds
        run: sleep 120s
        shell: bash
  test:
    uses: wlee221/changeset-poc/.github/workflows/tests.yml@main
    needs: remove-label
    with:
      ref: ${{ github.event.pull_request.head.sha }}
      repo: ${{ github.event.pull_request.head.repo.full_name }}
    secrets:
      USERNAME: ${{ secrets.USERNAME }}