name: PR Preview
on:
  pull_request:
    types: [synchronize]

jobs:
  Release-Snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          version: 14.x
      - name: Install Dependencies
        run: yarn
      - name: Exit prerelease mode if on
        run: |
          [ -f .changeset/pre.json ] && yarn changeset pre exit
      - name: Run changeset version
        run: yarn changeset version --snapshot pr-${{ github.event.number }}
      - name: Print package version changes
        run: cat ${{ github.workspace }}/packages/core/package.json
