name: Push to Fork PR

on:
  pull_request_target:
    branches: [main]
    types: [labeled]

permissions:
  pull-requests: write # used to remove label
  # other permissions are defaulted to "none"

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'run-tests'
    steps:
      - name: Remove run-tests label
        if: always()
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;
            const label = 'run-tests';
            github.issues.removeLabel({ owner, repo, issue_number, name: label });
      - name: Run tests
        uses: wlee221/changeset-poc/.github/workflows/tests.yml@main
        with:
          ref: ${{ github.ref }}
          repository: ${ github.event.pull_request.head.repo.full_name }}
