name: Push to PR

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: wlee221/changeset-poc/.github/workflows/tests.yml@main
        with:
          ref: ${{ github.ref }}
          repository: ${ github.event.pull_request.head.repo.full_name }}
