name: Receive Fork Approval

on: pull_request_review

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.review.commit_id }}
      - run: echo ${{ github.repository }}
      - run: echo ${{ github.event.pull_request.head.repo.full_name }}

  test:
    needs: echo
    uses: wlee221/changeset-poc/.github/workflows/tests.yml@main
    with:
      repo: ${{ github.event.pull_request.head.repo.full_name }}
      ref: ${{ github.event.review.commit_id }}
    secrets:
      USERNAME: ${{ secrets.USERNAME }}
