name: Test/internal-prs

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]
    
jobs:
  test:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    uses: wlee221/changeset-poc/.github/workflows/tests.yml@main
    with:
      ref: ${{ github.event.pull_request.head.ref }}
      repository: ${{ github.event.pull_request.head.repo.full_name }}
