name: Test / forks

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit to run tests against"
        required: true
      repository:
        description: "Fork repository to run tests against"
        required: true

jobs:
  test:
    uses: wlee221/changeset-poc/.github/workflows/tests.yml@main
    with:
      ref: ${{ inputs.commit }}
      repository: ${{ inputs.repository }}
    secrets:
      USERNAME: ${{ secrets.USERNAME }}

  status:
    runs-on: ubuntu-latest
    steps:
      - uses: LouisBrunner/checks-action@v1.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: PR Checks
          conclusion: "success"
          sha: ${{ inputs.commit }}
          output: "POC"
