name: Tests

on:
  workflow_call:
    inputs:
      ref:
        required: true  
        type: string
      repository:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
          repository: ${{ inputs.repository }}
          persist-credentials: false
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: "yarn"
      - name: Install packages
        run: yarn --frozen-lockfile
      - name: Build packages
        run: yarn build
      - name: Test packages
        run: yarn test
      - name: Sleep for 20 seconds
        run: sleep 20s
        shell: bash
