name: Tests

on:
  push:
    branches: [main]
    
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, labeled]

jobs:
  test:
    runs-on: ubuntu-latest

    # We run this workflow if it's:
    #   1) push to main, or
    #   2) pull request not from a fork, or
    #   3) pull request from a fork that has "run-tests" label
    if: |
      github.event_name == 'push' ||
      (github.event.pull_request.head.repo.full_name == github.repository) || 
      (github.event.action == 'labeled' && github.event.label.name == 'run-tests')
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event_name == 'push' && github.ref || github.event.pull_request.head.ref }}
          persist-credentials: false
      - name: Setup Node.js LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
          cache: "yarn"
      - name: Install packages
        run: yarn --frozen-lockfile
      - name: Build packages
        run: yarn build
      - name: Test packages
        run: yarn test
      - name: Sleep for 20 seconds
        run: sleep 20s
        shell: bash
      - name: Remove run-tests label
        if: always() && github.event.label.name == 'run-tests'
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue: { number: issue_number }, repo: { owner, repo } } = context;
            const label = 'run-tests';
            github.issues.removeLabel({ owner, repo, issue_number, name: label });
