name: Unpublish / manual

on:
  workflow_dispatch:
    inputs:
      dist-tag:
        type: choice
        description: npm dist tag to publish to
        options:
          - experimental
          - poc
        required: true

jobs:
  unpublish:
    strategy:
      matrix:
        package:
          - core
          - bar
          - foo
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Unpublish version
        run: npm unpublish "@wlee221-changeset-poc/$PACKAGE@$DIST_TAG"
        env:
          PACKAGE: ${{ matrix.package }}
          DIST_TAG: ${{ inputs.dist-tag }}
