name: Unpublish / manual

on:
  workflow_dispatch:
    inputs:
      dist-tag:
        type: choice
        description: npm dist tag to publish to
        options:
          - experimental
          - poc
        required: true

jobs:
  unpublish:
    strategy:
      matrix:
        package:
          - bar
          - foo
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Get version that dist-tag points to
        id: get-version
        run: |
          version="$(npm view @wlee221-changeset-poc/"$PACKAGE" dist-tags."$DIST_TAG")"
          echo "::set-output name=version::"$version""
        env:
          PACKAGE: ${{ matrix.package }}
          DIST_TAG: ${{ inputs.dist-tag }}
      - name: echo version
        run: echo ${{ steps.get-version.outputs.version }}
      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Unpublish version
        if: ${{ steps.get-version.outputs.version != '' }}
        run: npm unpublish @wlee221-changeset-poc/"$PACKAGE"@"$VERSION"
        env:
          VERSION: ${{ steps.get-version.outputs.version }}
          PACKAGE: ${{ matrix.package }}
